---
- name: (fusiondirectory) Fusion Directory conf is deployed
  template:
    src: "nginx_fusiondirectory.conf.j2"
    dest: "/var/lib/docker/volumes/nginx_conf.d/_data/{{ environment_domain }}/fusiondirectory.conf"
  notify: 'Restart Frontend'

- name: (fusiondirectory) The latest Fustion Directory service is built and {{ compositional_fusiondirectory_state }}
  docker_service:
    project_name: fusiondirectory
    definition:
      version: '3.6'
      services:
        ldap:
          image: tiredofit/openldap-fusiondirectory
          container_name: ldap
          hostname: ldap
          restart: always
          domainname: "{{ environment_domain }}"
          environment:
            DEBUG_MODE: 'TRUE'
            HOSTNAME: 'openldap-fusiondirectory'
            BACKEND: 'mdb'
            LOG_LEVEL: '256'
            DOMAIN: '{{ environment_domain }}'
            ADMIN_PASS: '{{ compositional_fusiondirectory_ldap_admin_pass }}'
            CONFIG_PASS: '{{ compositional_fusiondirectory_ldap_config_pass }}'
            FUSIONDIRECTORY_ADMIN_USER: 'fd-admin'
            FUSIONDIRECTORY_ADMIN_PASS: '{{ compositional_fusiondirectory_admin_pass }}'
            ORGANIZATION: '{{ environment_domain }}'
            BASE_DN: "{% for i in environment_domain.split('.') %}dc={{ i }}{% if not loop.last %},{% endif %}{% endfor %}"

          volumes:
            - backup:/data/backup
            - data:/var/lib/openldap
            - config:/etc/openldap/slapd.d

          networks:
            - 'identity'

        fusiondirectory:
          container_name: fusiondirectory
          restart: always
          image: tiredofit/fusiondirectory
          depends_on:
            - ldap

          environment:
            VIRTUAL_HOST: 'fusiondirectory'
            VIRTUAL_NETWORK: 'frontend'
            VIRTUAL_PORT: '80'
            PLUGIN_AUDIT: 'TRUE'
            PLUGIN_DSA: 'TRUE'
            PLUGIN_LDAPDUMP: 'TRUE'
            PLUGIN_LDAPMANAGER: 'TRUE'
            PLUGIN_MAIL: 'TRUE'
            PLUGIN_PERSONAL: 'TRUE'
            PLUGIN_PPOLICY: 'TRUE'
            PLUGIN_WEBSERVICE: 'TRUE'
            LDAP1_NAME: 'LDAP'
            LDAP1_HOST: 'ldap'
            LDAP1_PORT: '389'
            LDAP1_BASE_DN: "{% for i in environment_domain.split('.') %}dc={{ i }}{% if not loop.last %},{% endif %}{% endfor %}"
            LDAP1_ADMIN_DN: "cn=admin,{% for i in environment_domain.split('.') %}dc={{ i }}{% if not loop.last %},{% endif %}{% endfor %}"
            LDAP1_ADMIN_PASS: '{{ compositional_fusiondirectory_ldap_admin_pass }}'

          networks:
            - 'frontend'
            - 'identity'

      volumes:
        backup:
        data:
        config:
      networks:
        identity:
          name: 'identity'
        frontend:
          external: true

    build: "{{ compositional_fusiondirectory_build }}"
    state: "{{ compositional_fusiondirectory_state }}"
  register: compositional_fusiondirectory_output

- name: (fusiondirectory) Symlink fusiondirectory directory
  shell: docker exec -i fusiondirectory bash -c "ln -sT /www/fusiondirectory/html /www/fusiondirectory/html/fusiondirectory"
  when: compositional_fusiondirectory_output.changed
