---
- name: (ldapcherry) Nginx conf is deployed
  template:
    src: "nginx_ldapcherry.conf.j2"
    dest: "/var/lib/docker/volumes/nginx_conf.d/_data/{{ environment_domain }}/ldapcherry.conf"
  notify: 'Restart Frontend'

- name: (ldapcherry) The latest ldapcherry service is built and {{ compositional_ldapcherry_state }}
  docker_service:
    project_name: ldapcherry
    definition:
      version: '3.6'
      services:
          ldapcherry:
              image: 'smacz/ldapcherry:andrewcz-homelab-179'
              container_name: ldapcherry
              restart: always
              volumes:
                  - ldapcherry:/etc/ldapcherry

              networks:
                  - frontend
                  - identity

              environment:
                LDAP_DISPLAY_NAME: "'Compositional Enterprises'"
                LDAP_URI: "ldap://directory"
                LDAP_BINDDN: "cn=admin,{% for level in environment_domain.split('.') %}dc={{ level }}{% if not loop.last %},{% endif %}{% endfor %}"
                LDAP_PASSWORD: "{{ compositional_ldapcherry_admin_pass }}"
                SUFFIX: "{% for level in environment_domain.split('.') %}dc={{ level }}{% if not loop.last %},{% endif %}{% endfor %}"

          directory:
              image: mwaeckerlin/openldap
              container_name: directory
              restart: always
              environment:
                DOMAIN: "{{ environment_domain }}"
                PASSWORD: "{{ compositional_ldapcherry_admin_pass }}"

              volumes:
                  - ldap-db:/var/lib/ldap
                  - ldap-conf:/etc/ldap
                  - backups:/var/backups
                  - restore:/var/restore

              networks:
                  - identity

      volumes:
          ldap-db:
          ldap-conf:
          backups:
          restore:
          ldapcherry:

      networks:
          frontend:
              external: true

          identity:
              name: identity

    build: "{{ compositional_ldapcherry_build }}"
    state: "{{ compositional_ldapcherry_state }}"

  register: compositional_ldapcherry_output
