---
- name: (mariadb) The latest mariadb service is build and present
  docker_service:
    project_name: mariadb
    definition:
      version: '3.6'
      services:
          mariadb:
              image: "mariadb:{{ compositional_mariadb_version }}"
              container_name: database
              restart: always
              volumes:
                  - "/srv/{{ compositional_mariadb_storage }}/database_mysql:/var/lib/mysql"
                  - "/srv/{{ compositional_mariadb_storage }}/database_conf.d:/etc/mysql/conf.d"
              networks:
                  - backend
              environment:
                  MYSQL_ROOT_PASSWORD: "{{ compositional_database_root_password }}"
      networks:
          backend:
              name: backend
    build: "{{ compositional_mariadb_build }}"
    state: "{{ compositional_mariadb_state }}"
    restarted: "{{ compositional_mariadb_restarted }}"
  register: compositional_backend_output
  no_log: True

- name: (mariadb) Set Backend Type
  set_fact:
    compositional_backend_type: 'mysql'
    compositional_backend_port: '3306'
