---
- name: (mariadb) The latest mariadb service is built and present
  docker_compose:
    project_name: mariadb
    timeout: 60
    definition:
      version: '3.6'
      services:
          mariadb:
              image: "mariadb:{{ compositional_mariadb_version }}"
              container_name: database
              restart: always
              volumes:
                  - "/srv/{{ compositional_mariadb_storage }}/database_mysql:/var/lib/mysql"
                  - "/srv/{{ compositional_mariadb_storage }}/database_conf.d:/etc/mysql/conf.d"
              networks:
                  - backend
              environment:
                  MYSQL_ROOT_PASSWORD: "{{ compositional_database_root_password }}"
              healthcheck:
                test: "{{ compositional_mariadb_healthcheck }}"
                interval: 5s
                timeout: 30s
                retries: 3
      networks:
          backend:
              name: backend
    pull: "{{ compositional_mariadb_pull }}"
    state: "{{ compositional_mariadb_state }}"
    restarted: "{{ compositional_mariadb_restarted }}"
  register: compositional_backend_output
  no_log: "{{ compositional_no_log }}"

- name: (mariadb) Set Backend Type
  set_fact:
    compositional_backend_type: 'mysql'
    compositional_backend_port: '3306'
