---
# tasks file for role-compositional
- name: Install necessary packages
  apt:
    name: "{{ pkgs }}"
    state: latest
  vars:
    pkgs:
      - build-essential
      - libsystemd-dev

- name: Ensure that the local and remote directories are configured
  file:
    path: "/srv/{{ item }}"
    recurse: yes
    state: directory
  loop:
    - 'local'
    - 'remote'

- name: Set up PATH environment in the crontab
  cron:
    name: PATH
    env: yes
    job: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

- include_tasks: "./{{ item }}.yml"
  with_items:
    - "{{ compositional_frontend_service }}"
    - "{{ compositional_backend_service }}"

- name: Setup Services
  block:
    - include_tasks: "./{{ item }}.yml"
      with_items: "{{ compositional_services }}"

    - name: Trigger any container restarts here
      meta: flush_handlers

    - include_tasks: "./bind_mountpoints.yml"
      when: compositional_proxy_bind_mountpoints | length > 0

  when: compositional_setup_services | bool
